spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
