spring:
  application:
    name: backend

<<<<<<< HEAD
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/recruitment_scheduler?serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always
=======
>>>>>>> 328a103f05e25de067e97fa36d49e8263f4d08ca
  jpa:
    hibernate:
      ddl-auto: none

    jackson:
      property-naming-strategy: SNAKE_CASE